### ISSUE TITLE
Import Errors with services.py 

### ISSUE THREAD

**Issue by thaxy** [mixxorz/django-service-objects#18]
Hello, 

when I try to import a model at the top of my ``services.py`` module I get the following ``ImportError``:

```
...
django_1    |   File "/app/server/stations/models.py", line 9, in <module>
django_1    |     from .services import UpdateAlarmSensorsInDatabase
django_1    |   File "/app/server/stations/services.py", line 3, in <module>
django_1    |     from .models import BitSensorInformation
django_1    | ImportError: cannot import name 'BitSensorInformation'
```

``services.py``:

```
from service_objects.services import Service
from .models import BitSensorInformation  # causes the error

class UpdateAlarmSensorsInDatabase(Service):
 
     def process(self):
         # from .models import BitSensorInformation  # this would work
         print(BitSensorInformation.objects.all())
```

``models.py``:

```
from .services import UpdateAlarmSensorsInDatabase

class BitSensorInformation(models.Model):
    pass

class AnotherModel(models.Model):

    def save(self, *args, **kwargs):
        super().save(*args, **kwargs)
        UpdateAlarmSensorsInDatabase.execute({})
```

As you can see I need to execute the service object within the model save method. This leads to a cross import issue. Is there any advice you could give me? I try to avoid importing the model at function level.

**Comment by rhymes** [comment]
Why do you need the service object in the model?

If you look at the readme the service object controls and composes the models, not the other way around

**Comment by rhymes** [comment]
@thaxy I don't agree 100% with the idea of putting all the logic in the models but if you have to execute business logic everytime the model changes you can probably use signals: https://docs.djangoproject.com/en/2.0/topics/signals/

In the signal you call the service object and that's it.

**Comment by thaxy** [comment]
Thanks for your help. I will give signals a try.

**Comment by OmenApps** [comment]
For anyone else stumbling upon this, you can refer to the model lazily to accomplish this. Something like this in your services file:

`from django.apps import apps
`
Inside the service:

`BitSensorInformation = apps.get_model(app_label="app_name", model_name="model_name")
print(BitSensorInformation.objects.all())`
