### ISSUE TITLE
Double validation ?

### ISSUE THREAD

**Issue by isasiluispy** [mixxorz/django-service-objects#44]
Hi, I have a question, when you call the service say inside a view just like the example you gave, there's going to be a double validation right ? I mean, one from the form itself, and again from the service because its based on forms right ? Is this OK? Or will a feel a delay ? I copy the example from README for making myself clear. Thanks in advance.

```
# views.py

# Function Based View
def create_user_view(request):
    form = NewUserForm()
    if request.method == 'POST':
        form = NewUserForm(request.POST)

        if form.is_valid():
            try:
                CreateUser.execute(request.POST)
                return redirect('/success/')
            except Exception:
                form.add_error(None, 'Something went wrong')

    return render(request, 'registration/new-user.html', {'form': form})


# Class Based View
class CreateUserView(ServiceView):
    form_class = NewUserForm
    service_class = CreateUser
    template_name = 'registration/new-user.html'
    success_url = '/success/'
```

**Comment by isasiluispy** [comment]
@mixxorz

**Comment by mixxorz** [comment]
Yes. There will be double validation if this is used in conjunction with a regular form. Most of the time this won't be a problem, unless your validation logic is very complicated.

I know it's not the cleanest approach, but if you want to make sure your business rules are enforced, validation needs to be part of that.
