### ISSUE TITLE
Create new release

### ISSUE THREAD

**Issue by jackton1** [mixxorz/django-service-objects#47]
@mixxorz Any chance this could be deployed soon ?. Thanks

**Comment by peterfarrell** [comment]
@mixxorz ping - we'd really like the new release too. Would you like some help maintaining the project?

**Comment by mixxorz** [comment]
Sorry for the delay! I'll try to be more prompt next time. In the meantime, I've released v0.6.0.

**Comment by peterfarrell** [comment]
@mixxorz Thanks! Appreciate it. I'm maintainer (with release rights on PyPi) for Django PGCrypto Fields if you interested in some help with this project. https://github.com/incuna/django-pgcrypto-fields
