### ISSUE TITLE
MultipleModelField should accept other types as iterable not just list

### ISSUE THREAD

**Issue by peterfarrell** [mixxorz/django-service-objects#50]
It seems to me that MultipleModelField should accept any iterable such as a Django `queryset`, `tuple`, and `set` -- not just a `list`.

I commonly have forms using `forms.ModelMultipleChoiceField` which in the cleaned_data returns a queryset.  I am having to wrap `list` around the data from a `forms.ModelMultipleChoiceField` to coerce it into a list for the library.

Views.py:
```python
DuplicateMergeService.execute({
    'duplicates':list(form.cleaned_data['duplicates']),
    'by': request.user
})
```

 Seems like `MultipleModelField` should accept any iterable and not be restricted to `list`

**Comment by peterfarrell** [comment]
@jackton1 Thoughts? It would smooth out using the MultipleModelField. Right now you have to coerce all input to a MultipleModelField into a list before sending it in as input to the service. I'd be willing to put in a PR for this -- just don't want to waste my time if it won't be accepted.

**Comment by jackton1** [comment]
Personally switch from using the MultipleModelField -> forms.ModelMultipleChoiceField for queryset.
```python
my_models = forms.ModelMultipleChoiceField(queryset=MyModel.objects.all())
```

OR 
```python
recipients = forms.MultipleChoiceField(choices=[...])
```

**Comment by peterfarrell** [comment]
Thanks for the idea @jackton1. forms.ModelMultipleChoiceField would expect the input to be a list of PKs so you couldn't pass it a queryset or list of objects. In my use case, we already have a queryset to pass into the service so it would not be performant to convert a queryset into a list of PK only for forms.ModelMultipleChoiceField to transform those PKs back into a queryset.

This is why I was proposing that `service_objects.fields.ModelMultipleChoiceField` should accept any reasonable iterable containing model objects like queryset, list, set, or tuple -- not just a list.

**Comment by jackton1** [comment]
Yeah I can see an argument for switching to

```python
from collections import Iterable

...
        if not isinstance(values, Iterable):
            raise ValidationError(self.error_non_list)
```

Might have to rename `error_non_list` -> `error_non_iterable`


Question:
 For queryset's ensuring that `allow_unsaved` is always set to False since this is pulling a list of objects from the db.

```

if isinstance(values, QuerySet) and self.allow_unsaved:
   raise ValidationError('...')
```

**Comment by peterfarrell** [comment]
@jackton1 Thanks for the feedback and mentioning the allow_unsaved.  I guess @c17r already committed a change so I won't submit the PR I started last night. Glad to see this improvement.
