### ISSUE TITLE
 cannot import name 'six' from 'django.utils'

### ISSUE THREAD

**Issue by Singh-Sg** [mixxorz/django-service-objects#54]
I Looked that code(service_objects/services.py), this problem solved but i'm getting same error.
Could you please help my why after install latest version its not working?

My assumption: Code updated according to djagno3 but new build not updated on pip packages.

Please help me.
Thank you so much.

**Comment by jackton1** [comment]
This has been fixed with #53

**Comment by peterfarrell** [comment]
@jackton1 or @Singh-Sg Please close this ticket.
