### ISSUE TITLE
Custom cleaning of inputs

### ISSUE THREAD

**Issue by steezeburger** [mixxorz/django-service-objects#62]
Have you all thought about adding the possibility for custom cleaning? 

Or maybe some documentation about overriding `service_clean`?

I'd be happy to contribute if you all think either of those options are good ideas!

Love the repo by the way! Big fan of the philosophy.

**Comment by c17r** [comment]
The code is just a thin layer over Django’s Forms so any of the customizations mentioned here https://docs.djangoproject.com/en/3.1/ref/forms/validation/ like overriding clean() or using clean_<fieldname>() functions should work so unless you are thinking of something else there shouldn’t be a need for code changes. Always happy for documentation improvements.
