### ISSUE TITLE
Translate messages and documents to russian language

### ISSUE THREAD

**Issue by ivanscm** [mixxorz/django-service-objects#64]
Hello contributors! 

I want to translate the documentation into Russian. What is the best way to arrange translation files for documentation? Make a fork for the Russian language according to this documentation - [readthedocs localization](https://docs.readthedocs.io/en/stable/localization.html)?

**Comment by c17r** [comment]
Hello, thanks for your interest in the project!

1. Make a fork
2. Following the instructions at [Django translation steps](https://docs.djangoproject.com/en/3.1/topics/i18n/translation/)
3. Submit back a PR

**Comment by ivanscm** [comment]
@c17r done! Please check

**Comment by c17r** [comment]
Thanks for the contribution! Merged in.
