### ISSUE TITLE
Optionally execute without atomic transaction?

### ISSUE THREAD

**Issue by editkid** [mixxorz/django-service-objects#8]
Hello! I'm currently handling a case where if a service's execution fails I want to be left with a record of the failure in the database. This means I'm overriding the `execute` class method on `Service` to remove the following line:
```
with transaction.atomic():
```

I wonder if transactionality could be a configurable option on the `Service` class?

**Comment by mixxorz** [comment]
Interesting.

Can you share more specifics on why you want to remove the transaction? I was thinking maybe it's probably better to use a try catch block.

**Comment by editkid** [comment]
Yeah, let me try to illustrate it better with an example.

Inside our `process` call it goes a little like this currently:

```
    def process(self):
        """
        The business logic of creating a new loan.
        :return:
        """
        try:

            api = ExternalAPI()
            # The next step creates a "loan" instance with an external service
            status, loan_instance = api.loans.create(loan_data)

        except Exception:

            # This effectively withdraws the externally-stored loan instance and
            # keeps a record of this withdrawal in the local database.
            # Critically, because of the atomic transaction this local record would be undone!
            if loan_instance:
                transaction = LoanTransaction(loan=loan_instance)
                transaction.create_withdraw()
                api.loans.withdraw(loan_instance)

            raise
```

In a nutshell, while it's sometimes handy to have the atomic transaction, I don't think something as neutral and basic as a `Service` class should assume that we always have database events that we want to wrap into a transaction.

Keen to hear your view!

**Comment by mixxorz** [comment]
Ah. So you want to handle the exception elsewhere, but at the same time keep a record. Okay I think that's a pretty valid use case. I would like to keep the default behavior of it being a transaction, but I'm totally open to having a feature flag or whatever to disable it.

Do you have suggestions for what the API for that will look like...?

**Comment by editkid** [comment]
Potentially the easiest would be a parameter for `execute`, e.g.:
```
    @classmethod
    def execute(cls, inputs, files=None, db_transaction=True, **kwargs):
```

**Comment by mixxorz** [comment]
Maybe a class attribute as well? What do you think?

```
class SomeService(Service):
    db_transaction = False
```

**Comment by editkid** [comment]
Oh! I see now. You set it when you extend the `Service` class! Love it.

**Comment by mixxorz** [comment]
Okay I think that looks good. Do you mind submitting a PR for this?

**Comment by editkid** [comment]
Sure thing.
